package modelos;
// Generated Jun 11, 2023 4:14:04 PM by Hibernate Tools 4.3.1



/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private int id;
     private String nome;
     private String apelido;
     private String cargo;
     private String sexo;

    public Funcionario() {
    }

    public Funcionario(int id, String nome, String apelido, String cargo, String sexo) {
       this.id = id;
       this.nome = nome;
       this.apelido = apelido;
       this.cargo = cargo;
       this.sexo = sexo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getApelido() {
        return this.apelido;
    }
    
    public void setApelido(String apelido) {
        this.apelido = apelido;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }




}


