package modelos;
// Generated Jun 11, 2023 4:14:04 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Servico generated by hbm2java
 */
public class Servico  implements java.io.Serializable {


     private int id;
     private String nome;
     private double preco;
   

    public Servico() {
    }

    public Servico(int id, String nome, double preco) {
       this.id = id;
       this.nome = nome;
       this.preco = preco;
      
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public double getPreco() {
        return this.preco;
    }
    
    public void setPreco(double preco) {
        this.preco = preco;
    }
 



}


