package modelos;
// Generated May 31, 2023 10:36:18 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Servico generated by hbm2java
 */
public class Servico  implements java.io.Serializable {


     private int id;
     private String nome;
     private double preco;
     private Date marcacao;
     private int idCliente;

    public Servico() {
    }

    public Servico(int id, String nome, double preco, Date marcacao, int idCliente) {
       this.id = id;
       this.nome = nome;
       this.preco = preco;
       this.marcacao = marcacao;
       this.idCliente = idCliente;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public double getPreco() {
        return this.preco;
    }
    
    public void setPreco(double preco) {
        this.preco = preco;
    }
    public Date getMarcacao() {
        return this.marcacao;
    }
    
    public void setMarcacao(Date marcacao) {
        this.marcacao = marcacao;
    }
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }




}


